name: Track Stars

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "6 1-23/2 * * *"


jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self-use branch if possible
        id: checkout-self-use
        if: ${{ github.event_name == 'schedule' }} 
        continue-on-error: true
        run: |
          cd ../
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY --depth=1 -b self-use

      - name: Checkout code (default)
        if: ${{ github.event_name != 'schedule' || steps.checkout-self-use.outcome == 'failure' }} 
        uses: actions/checkout@v3

      - name: Install aiohttp
        run: yes | pip install aiohttp

      - name: Run script
        env:
          MY_TOKEN: ${{ secrets.MY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: python tracker.py
